### ISSUE TITLE
S3 error: You must provide the Content-Length HTTP header

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#188]
When pushing Docker image, I got 500 error from stacktrace from S3 client `You must provide the Content-Length HTTP header`. It seems the request contains `Content-Length` header, but it was not provided to S3 storage:
```
artipie    | 
artipie    | [INFO] 2020-06-05 14:00:58,800 vert.x-eventloop-thread-1 com.artipie.http.async.AsyncSlice - >> PATCH /public/docker/v2/alpine/blobs/uploads/4741e16d-3190-4391-a925-4b40cb3dd957 HTTP_1_0
artipie    | 
artipie    | Host: central.artipie.com
artipie    | X-Real-IP: x.x.x.x
artipie    | X-Forwarded-For: x.x.x.x
artipie    | Connection: close
artipie    | Content-Length: 2757034
artipie    | User-Agent: docker/19.03.8...
artipie    | Accept-Encoding: gzip
artipie    | [INFO] 2020-06-05 14:00:59,078 sdk-async-response-11-0 com.artipie.asto.s3.S3Storage - List 'docker/docker/registry/v2/repositories/alpine/_uploads/4741e16d-3190-4391-a925-4b40cb3dd957': 1
artipie    | [INFO] 2020-06-05 14:00:59,140 sdk-async-response-11-1 com.artipie.asto.s3.S3Storage - Size 'docker/docker/registry/v2/repositories/alpine/_uploads/4741e16d-3190-4391-a925-4b40cb3dd957/data': 0
artipie    | [INFO] 2020-06-05 14:00:59,219 sdk-async-response-11-2 com.artipie.http.async.AsyncSlice - Failure: java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: You must provide the Content-Length HTTP header. (Service: S3, Status Code: 411, Request ID: 0000017284C8EA1D8019A0141AC32C96)
artipie    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)
artipie    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.uniHandle(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie    | 	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:75)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(Unknown Source)
artipie    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryResponseIfNeeded(AsyncRetryableStage.java:156)
artipie    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:120)
artipie    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:107)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie    | 	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$1(MakeAsyncHttpRequestStage.java:138)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
artipie    | 	at java.base/java.lang.Thread.run(Unknown Source)
artipie    | Caused by: software.amazon.awssdk.services.s3.model.S3Exception: You must provide the Content-Length HTTP header. (Service: S3, Status Code: 411, Request ID: 0000017284C8EA1D8019A0141AC32C96)
artipie    | 	at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:95)
artipie    | 	at software.amazon.awssdk.services.s3.model.S3Exception$BuilderImpl.build(S3Exception.java:55)
artipie    | 	at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:127)
artipie    | 	at software.amazon.awssdk.protocols.query.unmarshall.AwsXmlErrorProtocolUnmarshaller.handle(AwsXmlErrorProtocolUnmarshaller.java:86)
artipie    | 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:88)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie    | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie    | 	at software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:129)
artipie    | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:180)
artipie    | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:67)
artipie    | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:296)
artipie    | 	at com.typesafe.netty.HandlerPublisher.publishMessage(HandlerPublisher.java:362)
artipie    | 	at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:304)
artipie    | 	at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258)
artipie    | 	at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41)
artipie    | 	at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452)
artipie    | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
artipie    | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
artipie    | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
artipie    | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
artipie    | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
artipie    | 	... 1 more
artipie    | 
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)
