### ISSUE TITLE
500 error on image upload

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#212]
I tried to upload Docker image but got 500 error with the stacktrace:
```
artipie         | [WARN] 2020-06-15 14:17:27,670 aws-java-sdk-NettyEventLoop-1-0 software.amazon.awssdk.http.nio.netty.internal.UnusedChannelExceptionHandler - A non-I/O exception occurred on a channel (5f86a3a7) that was not in use. The channel has been closed to prevent any ongoing issues.
artipie         | io.netty.channel.ChannelPipelineException: com.typesafe.netty.http.HttpStreamsHandler$1.handlerRemoved() has thrown an exception.
artipie         | 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:640)
artipie         | 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)
artipie         | 	at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)
   ...
artipie         | Caused by: java.lang.NoSuchMethodError: 'void com.artipie.asto.fs.RxFile.<init>(java.nio.file.Path, io.vertx.reactivex.core.file.FileSystem)'
artipie         | 	at com.artipie.docker.asto.AstoBlobs.lambda$put$5(AstoBlobs.java:115)
artipie         | 	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback.onSuccess(SingleFlatMap.java:76)
artipie         | 	at io.reactivex.internal.observers.ResumeSingleObserver.onSuccess(ResumeSingleObserver.java:46)
artipie         | 	at io.reactivex.internal.operators.single.SingleJust.subscribeActual(SingleJust.java:30)
artipie         | 	at io.reactivex.Single.subscribe(Single.java:3603)
artipie         | 	at io.reactivex.internal.operators.single.SingleDelayWithCompletable$OtherObserver.onComplete(SingleDelayWithCompletable.java:69)
artipie         | 	at io.reactivex.internal.operators.completable.CompletablePeek$CompletableObserverImplementation.onComplete(CompletablePeek.java:115)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableFlatMapCompletableCompletable$FlatMapCompletableMainSubscriber.onComplete(FlowableFlatMapCompletableCompletable.java:165)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:180)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:67)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:296)
artipie         | 	at com.typesafe.netty.HandlerPublisher.complete(HandlerPublisher.java:408)
artipie         | 	at com.typesafe.netty.HandlerPublisher.handlerRemoved(HandlerPublisher.java:395)
artipie         | 	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:979)
artipie         | 	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
artipie         | 	... 49 more
```
It seems asto version is outdated, and it can be fixed by updating dependency to latest `0.22` version: https://github.com/artipie/asto/releases/tag/0.22

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2.4`

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#218](https://github.com/artipie/docker-adapter/issues/218) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#218](https://github.com/artipie/docker-adapter/issues/218) is solved here.
