### ISSUE TITLE
NullPointerException when reading JsonManifest

### ISSUE THREAD

**Issue by g4s8** [artipie/docker-adapter#215]
I tried to push docker image to latest version of artipie registry:
```
docker push central.artipie.com/alpine:3.10
The push refers to repository [central.artipie.com/alpine]
77cae8ab23bf: Pushed 
[DEPRECATION NOTICE] registry v2 schema1 support will be removed in an upcoming release. Please contact admins of the central.artipie.com registry NOW to avoid future disruption. More information at https://docs.docker.com/registry/spec/deprecated-schema-v1/
received unexpected HTTP status: 500 Internal Server Error
```

But it fails with 500 error after push:
```
artipie         | [INFO] 2020-06-16 02:54:59,584 aws-java-sdk-NettyEventLoop-1-1 com.artipie.http.async.AsyncSlice - Failure: java.util.concurrent.CompletionException: java.lang.NullPointerException
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
artipie         | 	at java.base/java.util.concurrent.CompletableFuture.complete(Unknown Source)
artipie         | 	at io.reactivex.internal.observers.ConsumerSingleObserver.onSuccess(ConsumerSingleObserver.java:62)
artipie         | 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
artipie         | 	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
artipie         | 	at io.reactivex.internal.operators.flowable.FlowableReduceSeedSingle$ReduceSeedObserver.onComplete(FlowableReduceSeedSingle.java:110)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:180)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$500(ResponseHandler.java:67)
artipie         | 	at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:296)
artipie         | 	at com.typesafe.netty.HandlerPublisher.publishMessage(HandlerPublisher.java:362)
artipie         | 	at com.typesafe.netty.HandlerPublisher.flushBuffer(HandlerPublisher.java:304)
artipie         | 	at com.typesafe.netty.HandlerPublisher.receivedDemand(HandlerPublisher.java:258)
artipie         | 	at com.typesafe.netty.HandlerPublisher.access$200(HandlerPublisher.java:41)
artipie         | 	at com.typesafe.netty.HandlerPublisher$ChannelSubscription$1.run(HandlerPublisher.java:452)
artipie         | 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
artipie         | 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
artipie         | 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
artipie         | 	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
artipie         | 	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
artipie         | 	at java.base/java.lang.Thread.run(Unknown Source)
artipie         | Caused by: java.lang.NullPointerException
artipie         | 	at com.artipie.docker.manifest.JsonManifest.lambda$config$2(JsonManifest.java:91)
artipie         | 	... 21 more
```

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) I'm not managing this repo, remove the [webhook](https://github.com/artipie/docker-adapter/settings/hooks) or contact me in Slack, as explained in [§11](http://www.zerocracy.com/policy.html#11); I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11) /cc @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@69479bfe-25b6-466a-835a-a020547757e2, thread: pool-422-thread-1
com.zerocracy.radars.github.ThrottledComments[74] java.lang.IllegalStateException: Can't post an identical message to artipie/docker-adapter#215: I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, 
```

[0.53.15](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#215, Action: `assigned`

**Comment by olegmoz** [comment]
@rultor release, tag=`0.2.5`

**Comment by 0crat** [comment]
I'm not managing `artipie/docker-adapter` GitHub repository, you have to contact me in Slack first, see [§11](http://www.zerocracy.com/policy.html#11)
